# Generated by Django 4.0.2 on 2022-12-12 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_song_artwork'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='song',
            options={'ordering': ['title']},
        ),
        migrations.AddField(
            model_name='song',
            name='show',
            field=models.BooleanField(default=True),
        ),
    ]
