# Generated by Django 4.0.2 on 2023-01-05 10:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_checkoutinitiated'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutinitiated',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
