# Generated by Django 4.0.2 on 2022-05-06 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('filename', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200, null=True)),
                ('album', models.CharField(max_length=200, null=True)),
                ('artist', models.CharField(max_length=200, null=True)),
                ('genre', models.CharField(max_length=200, null=True)),
                (
                    'artwork',
                    models.ImageField(null=True, upload_to='media/albumArts'),
                ),
                ('file', models.FileField(upload_to='media/audio')),
            ],
        ),
    ]
