# Generated by Django 4.0.2 on 2022-05-07 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_song_artwork_alter_song_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='artwork',
            field=models.ImageField(max_length=255, null=True, upload_to='albumArts'),
        ),
    ]
